In [1]:
import numpy as np

Size, Shape, Dtype, ndim

In [4]:
vektor = np.array([1, 2, 3, 4, 5, 6])
matris = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
print(vektor)

[1 2 3 4 5 6]


In [6]:
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Size kaç elemandan oluştuğunu verir

In [8]:
vektor.size

6

In [9]:
matris.size

9

Shape şeklini verir

In [10]:
vektor.shape

(6,)

In [11]:
matris.shape

(3, 3)

ndim = uzayda kapladığı boyut

In [12]:
vektor.ndim

1

In [13]:
matris.ndim

2

dtype = veri tipi

In [14]:
vektor.dtype

dtype('int64')

In [15]:
matris.dtype

dtype('int64')

tipi

In [16]:
type(vektor)

numpy.ndarray

In [17]:
type(matris)

numpy.ndarray

Type Casting

In [19]:
sayilar = np.array([1,2,3,4,5.0,6])
print(sayilar.dtype)

float64


In [20]:
sayilar = sayilar.astype("int64")
print(sayilar.dtype)

int64


In [22]:
sayilar = np.array([1,2,3,4,5,6], dtype="int8")
print(sayilar, sayilar.dtype)

[1 2 3 4 5 6] int8


In [23]:
tarih = np.array(["2023-01-01"])
tarih.dtype

dtype('<U10')

In [24]:
tarih = tarih.astype("datetime64")
tarih.dtype

dtype('<M8[D]')

Matrislerde slice

In [27]:
matris = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
print(matris[0])

[1 2 3]


In [30]:
print(matris[1])

[4 5 6]


In [32]:
print(matris[1:3])

[[4 5 6]
 [7 8 9]]


In [33]:
print(matris[:,0])

[1 4 7]


In [34]:
print(matris[:,1:3])

[[2 3]
 [5 6]
 [8 9]]


In [35]:
print(matris[1:2,1:2])

[[5]]


Random matris oluşturma

In [54]:
np.random.randint(0,5,(4,4))

array([[4, 1, 1, 4],
       [1, 3, 1, 2],
       [0, 4, 4, 0],
       [3, 2, 0, 4]])

In [61]:
np.random.randint(0,10,(4,4))/10

array([[0.4, 0.2, 0.8, 0.9],
       [0.4, 0.9, 0.5, 0.4],
       [0.6, 0.4, 0.2, 0.2],
       [0.7, 0.9, 0.9, 0.7]])