In [2]:
import numpy as np

Mantıksal operatörler ve filtreleme

In [3]:
matris = np.random.randint(0,10,(5,5))

In [4]:
matris

array([[6, 7, 1, 5, 1],
       [8, 1, 3, 2, 0],
       [6, 8, 6, 6, 4],
       [7, 6, 4, 3, 5],
       [8, 3, 6, 9, 8]])

In [5]:
matris >5

array([[ True,  True, False, False, False],
       [ True, False, False, False, False],
       [ True,  True,  True,  True, False],
       [ True,  True, False, False, False],
       [ True, False,  True,  True,  True]])

In [6]:
matris[matris>5]

array([6, 7, 8, 6, 8, 6, 6, 7, 6, 8, 6, 9, 8])

In [7]:
matris[matris<5]

array([1, 1, 1, 3, 2, 0, 4, 4, 3, 3])

In [8]:
matris[matris==5]

array([5, 5])

In [9]:
matris[matris == 5].size

2

In [10]:
matris[matris != 7]

array([6, 1, 5, 1, 8, 1, 3, 2, 0, 6, 8, 6, 6, 4, 6, 4, 3, 5, 8, 3, 6, 9,
       8])

In [12]:
matris%2 == 0

array([[ True, False, False, False, False],
       [ True, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True, False, False],
       [ True, False,  True, False,  True]])

In [18]:
sifir = matris != 0
cift = matris%2 == 0
bir = matris == 1

In [16]:
matris [ cift & sifir]

array([6, 8, 2, 6, 8, 6, 6, 4, 6, 4, 8, 6, 8])

In [17]:
matris[cift | sifir]

array([6, 7, 1, 5, 1, 8, 1, 3, 2, 0, 6, 8, 6, 6, 4, 7, 6, 4, 3, 5, 8, 3,
       6, 9, 8])

In [20]:
matris[(cift & sifir) | bir]

array([6, 1, 1, 8, 1, 2, 6, 8, 6, 6, 4, 6, 4, 8, 6, 8])

In [21]:
m2 = np.full((5,5),5)

In [22]:
m2

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [24]:
m2[(cift & sifir) | bir]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])