The Basics

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
#get dimension
a.ndim

1

In [6]:
#get shape
a.shape

(3,)

Numpy ile Nokta, Doğru, Düzlem ve Uzay

In [3]:
skaler = np.array(90)
print(skaler)

90


In [5]:
vectorel = np.array([1,2,3,4,5])
print(vectorel)

[1 2 3 4 5]


In [6]:
matrices = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrices)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
tensor = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(tensor)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Neden NumPy

In [10]:
import time
liste = []
z1 = time.time()
for a in range(1_000_000):
    kuvvet = a**100
    liste.append(kuvvet)
z2 = time.time()
print(z2-z1)


1.5313920974731445


In [11]:
z3= time.time()
liste2 = np.arange(1_000_000)**100
z4 = time.time()
print(z4 - z3)

0.011622905731201172


Index ve Slice

In [16]:
vektor = np.array([0,2,4,5,6,7,8,15])
a = vektor[3]
b = vektor[0]
c = vektor[-1]
d = vektor[1:3]
e = vektor[2:6:2]
print(a,b,c,d,e)

5 0 15 [2 4] [4 6]
