In [1]:
import numpy as np

copy() ve view() metotları

In [3]:
matris = np.random.randint(0,5,(4,4))
matris

array([[3, 0, 1, 4],
       [3, 2, 2, 1],
       [1, 4, 3, 4],
       [1, 0, 0, 1]])

In [5]:
matris2 = matris.view()

In [9]:
matris2[0] = [9,9,9,9]
matris2

array([[9, 9, 9, 9],
       [3, 2, 2, 1],
       [1, 4, 3, 4],
       [1, 0, 0, 1]])

In [10]:
matris

array([[9, 9, 9, 9],
       [3, 2, 2, 1],
       [1, 4, 3, 4],
       [1, 0, 0, 1]])

In [11]:
matris3 = np.random.randint(0,5,(4,4))

In [12]:
matris3

array([[0, 1, 1, 0],
       [1, 0, 1, 4],
       [4, 3, 0, 0],
       [2, 0, 4, 3]])

In [13]:
matris4 = matris3.copy()
matris4

array([[0, 1, 1, 0],
       [1, 0, 1, 4],
       [4, 3, 0, 0],
       [2, 0, 4, 3]])

In [16]:
matris4[0] = [9,9,9,9]
matris4

array([[9, 9, 9, 9],
       [1, 0, 1, 4],
       [4, 3, 0, 0],
       [2, 0, 4, 3]])

In [17]:
matris3

array([[0, 1, 1, 0],
       [1, 0, 1, 4],
       [4, 3, 0, 0],
       [2, 0, 4, 3]])

ones(), zeros(), full() matris oluşturma metotları

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones(shape=(4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.full((4,4),19)

array([[19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19]])

eye(), diag(), identity() metotları

In [22]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.diag([1,1,1,1])

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [27]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])