In [1]:
import numpy as np

Arange ile Vektör Oluşturma

In [2]:
liste = [1, 2, 3, 4, 5, 6]
range(100000000000)

range(0, 100000000000)

In [3]:
milyon = np.arange(1000000000)

In [6]:
print(milyon)

[        0         1         2 ... 999999997 999999998 999999999]


In [5]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(np.arange(5,10,2))

[5 7 9]


linspace() ile vektör oluşturma

In [8]:
# 0 la 20 arasını 10 eşit parçaya böl
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [9]:
bol = np.linspace(5,25,15)
print(bol)

[ 5.          6.42857143  7.85714286  9.28571429 10.71428571 12.14285714
 13.57142857 15.         16.42857143 17.85714286 19.28571429 20.71428571
 22.14285714 23.57142857 25.        ]


In [11]:
print(bol[1]-bol[0] )
print(bol[3]-bol[2])

1.4285714285714288
1.428571428571427


Yeniden Boyutlandırma reshape()

In [12]:
m1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [13]:
print(m1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
m1.shape

(3, 4)

In [15]:
m1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
m1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [17]:
m1.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
np.linspace(0,20,30).reshape(6,5)

array([[ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069],
       [ 3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655],
       [ 6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241],
       [10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828],
       [13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414],
       [17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ]])